feat: progressText
Partnus/Timer pull request #7
Opened 2022-02-10 02:34 UTC by leejudy1017

### [Front]

### 제목

- progressText 추가

### 작업 내용

- TimerType PROGRESS_TEXT 기능 추가
- Progressable interface에 setProgressTextSize (ProgressText 사이즈 설정) 함수 추가
- MainActivty2 에서 progressText 테스트 가능

2022-02-10 12:43 UTC, JeonK1 requested changes
확인 완료했습니다! 고생하셨어요 ㅎㅎ

review 내용 요약
1. [질문] progressable 에 setProgressTextSize 가 있는 것은 progressbar 등에서도 TextView 를 통해 시간을 보여주는 기능이 추가될수도 있다는 점 때문이 맞을까요?
2. [요청] progressText에서 xml을 통해 받는 값 이름, progressSize -> progressTextSize 와 같은 느낌으로 text size를 변경하는 것을 보여주는 이름으로 변경 부탁드려요
3. [요청] TimerType 쪽 PROGRESS_RING 주석만 풀고 바로 추가할 수 있도록 위치 이동 부탁드려요

2022-02-10 12:43 UTC, JeonK1 commented on Timer/src/main/java/com/partnus/timer/TimerType.kt
>  }
```suggestion
enum class TimerType {
    PROGRESS_BAR,
    PROGRESS_TEXT,
    /*PROGRESS_RING*/
```
styleable에서 progressText가 value=1 이고, progressRing이 value=2 이기 때문에 실수 방지를 위해 PROGRESS_RING 을 마지막으로 보내주시면 좋을 것 같아요!
-> 여기서 주석만 풀어버리면.. ENUM 결과가 PROGRESS_RING이 1이 되고, PROGRESS_TEXT가 2가 되어서 에러가 발생할 것 같아요.. ㅠㅠ

2022-02-10 12:43 UTC, JeonK1 commented on Timer/src/main/res/values/styleable.xml
> +        <attr name="progressSize" format="float"/>
```suggestion
        <attr name="progressTextSize" format="float"/>
```
progressSize 라고 이름을 짓기엔 bar의 size인지 text의 size인지 혼동이 올 것 같아서 progressTextSize 와 같은... text라는 것을 인식할 수 있을 것 같은 이름으로 바꾸는 것이 좋을 것 같아요!

2022-02-10 12:43 UTC, JeonK1 commented on Timer/src/main/java/com/partnus/timer/TimerProgressBar.kt
>  }
현재 이 부분은 progress bar 쪽에 추가적인 기능으로 남은 시간을 TextView로 보여줄 수도 있다는 점 때문에 TODO로 비워져있는 것이 맞을까요..?

2022-02-10 14:09 UTC, KimHyungSik approved these changes

2022-02-10 14:34 UTC, JeonK1 approved these changes

2022-02-11 07:15 UTC, nosorae approved these changes

2022-02-15 14:04 UTC, merged